'use stricts';
import type { Metadata } from 'next';
import './globals.css';
import { Web3Provider } from '../../context/Web3Modal';
import { TokenChainListProvider } from '../../context/TokenChainList';
import Stars from '../../components/Stars';
import { cookieToInitialState } from 'wagmi';
import { config } from '../../config';
import { headers } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));
  return (
    <html lang="en">
      <body>
        <Stars />
        <TokenChainListProvider>
          <Web3Provider initialState={initialState}>{children}</Web3Provider>
        </TokenChainListProvider>
      </body>
    </html>
  );
}
